paths:
  base_dir: .
  input_dir: data/input
  output_dir: data/output
  artifacts_dir: data/artifacts

model:
  target: "Anemia"         # multiclase: No, Leve, Moderada, Severa
  algorithm: "xgb"         # xgb o rf
  random_state: 42
  test_size: 0.2

xgb_params:
  n_estimators: 300
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.9
  colsample_bytree: 0.9
  objective: "multi:softprob"

rf_params:
  n_estimators: 300
  n_jobs: -1
  random_state: 42
